#!/usr/bin/env bash
# Bash script that displays Best School 10 times
counter=1
while [ $counter -le 10 ]; do
  if [ $counter -eq 9 ]; then
    echo -e "Best School\nHi"
  else
    echo "Best School"
  fi
  ((counter++))
done
